### ISSUE TITLE
Bug with HasData

### ISSUE THREAD

**Issue by Justinfan827** [Basis-Theory/basistheory-go#69]
For additional support or to discuss issues/features, please reach out to us on our [Community](https://community.basistheory.com) or via email at [support@basistheory.com](mailto:support@basistheory.com)

https://github.com/Basis-Theory/basistheory-go/blob/master/model_token.go#L173

## Expected Behavior
- HasData should return nil if token data is nil

## Actual Behavior
- Logic is inverted

## Steps to Reproduce the Problem
  1. Create a token via dashboard
  2. Fetch token and call token.HasData()
  1. HasData() returns false when token.Data is populated

## Specifications
  - SDK Version: 3.10.0
  - Go Version: 1.20.2

**Comment by jleon15** [comment]
> https://github.com/Basis-Theory/basistheory-go/blob/master/model_token.go#L173
> 
> ## Expected Behavior
> * HasData should return nil if token data is nil

Hey @Justinfan827, this SDK is auto generated using OpenApi Generator and they had the logic wrong in the template. We have overridden it and this is now fixed in version [3.11.0 ](https://github.com/Basis-Theory/basistheory-go/releases/tag/v3.11.0)
